[2024-03-30 20:04:56,042] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:04:56] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:07:06,803] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:07:06] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:07:29,780] WARNING login() L91   Erro ao buscar o usu√°rio 'a2.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:07:29,781] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:07:29] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:08:27,716] WARNING login() L91   Erro ao buscar o usu√°rio 'A2a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:08:27,716] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:08:27] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:09:03,170] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:09:03,170] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:09:03] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:09:23,042] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:09:23] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:51:31,109] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:51:31,110] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:51:31] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:54:22,691] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.cc', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:54:22,692] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:54:22] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:54:24,492] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.cc', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:54:24,492] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:54:24] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:57:09,036] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:57:09,036] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:57:09] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 20:58:01,176] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 20:58:01,176] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 20:58:01] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:01:38,640] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:01:38,640] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:01:38] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:03:49,724] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:03:49,725] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:03:49] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:04:21,802] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:04:21,802] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:04:21] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:04:37,352] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:04:37] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:04:52,438] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:04:52] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:05:29,229] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:05:29,230] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:05:29] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:05:53,037] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:05:53] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:07:47,863] WARNING login() L91   Erro ao buscar o usu√°rio 'a@a.c', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:07:47,864] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:07:47] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:08:19,443] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:08:19] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:09:15,712] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:09:15] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:09:31,335] WARNING login() L91   Erro ao buscar o usu√°rio 'admin@admin.com', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:09:31,336] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:09:31] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:10:32,782] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:10:32] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:10:45,318] WARNING login() L91   Erro ao buscar o usu√°rio 'admin@admin.com', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:10:45,319] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:10:45] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:31:21,132] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:31:21,132] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:31:51,557] WARNING login() L91   Erro ao buscar o usu√°rio 'A@A.C', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
[2024-03-30 21:31:51,557] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:31:51] "[31m[1mPOST /login HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:32:32,780] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:32:32] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:34:08,067] INFO _log() L96   127.0.0.1 - - [30/Mar/2024 21:34:08] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-30 21:34:27,528] WARNING login() L91   Erro ao buscar o usu√°rio 'admin@admin.com', Senha ou email n√£o encontrado no sistema :/ - call_trace=/home/slsn/repos/bop_land_api/app.py L91  
